### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by mmanoj** [quiqfield/flowatcher#1]
Hi @quiqfield 

I'm getting below error while compilation, Please advice.

------------------- Build Flowatcher -------------------
  CC src/main.o
  CC src/init.o
  CC src/process_skelton.o
  CC src/process_monitor.o
  CC src/lws_callback_http.o
  CC src/get_app_status.o
  CC src/process_rx_flow.o
  CC src/flowtable.o
In file included from /opt/flowatcher/src/init.c:1:0:
/opt/flowatcher/src/main.h:34:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
/opt/flowatcher/deps/dpdk/mk/internal/rte.compile-pre.mk:126: recipe for target 'src/init.o' failed
make[1]: *** [src/init.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /opt/flowatcher/src/get_app_status.c:1:0:
/opt/flowatcher/src/main.h:34:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
/opt/flowatcher/deps/dpdk/mk/internal/rte.compile-pre.mk:126: recipe for target 'src/get_app_status.o' failed
make[1]: *** [src/get_app_status.o] Error 1
In file included from /opt/flowatcher/src/lws_callback_http.c:1:0:
/opt/flowatcher/src/main.h:34:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
/opt/flowatcher/deps/dpdk/mk/internal/rte.compile-pre.mk:126: recipe for target 'src/lws_callback_http.o' failed
make[1]: *** [src/lws_callback_http.o] Error 1
In file included from /opt/flowatcher/src/process_skelton.c:1:0:
/opt/flowatcher/src/main.h:34:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
/opt/flowatcher/deps/dpdk/mk/internal/rte.compile-pre.mk:126: recipe for target 'src/process_skelton.o' failed
make[1]: *** [src/process_skelton.o] Error 1
In file included from /opt/flowatcher/src/main.c:1:0:
/opt/flowatcher/src/main.h:34:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
/opt/flowatcher/deps/dpdk/mk/internal/rte.compile-pre.mk:126: recipe for target 'src/main.o' failed
make[1]: *** [src/main.o] Error 1
In file included from /opt/flowatcher/src/process_monitor.c:1:0:
/opt/flowatcher/src/main.h:34:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
/opt/flowatcher/deps/dpdk/mk/internal/rte.compile-pre.mk:126: recipe for target 'src/process_monitor.o' failed
make[1]: *** [src/process_monitor.o] Error 1
In file included from /opt/flowatcher/src/process_rx_flow.c:1:0:
/opt/flowatcher/src/main.h:34:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
/opt/flowatcher/deps/dpdk/mk/internal/rte.compile-pre.mk:126: recipe for target 'src/process_rx_flow.o' failed
make[1]: *** [src/process_rx_flow.o] Error 1
/opt/flowatcher/deps/dpdk/mk/rte.extapp.mk:42: recipe for target 'all' failed
make: *** [all] Error 2
root@infini:/opt/flowatcher# cd ..
root@infini:/opt# git clone https://github.com/akiskourtis/vtc-sriov-dpdk.git
Cloning into 'vtc-sriov-dpdk'...
remote: Counting objects: 3246, done.
remote: Total 3246 (delta 0), reused 0 (delta 0), pack-reused 3246
Receiving objects: 100% (3246/3246), 37.14 MiB | 737.00 KiB/s, done.
Resolving deltas: 100% (1522/1522), done.
Checking connectivity... done.

**Comment by mmanoj** [comment]
Also let me know which version of DPDK get cloned while downloading via get clone?

**Comment by quiqfield** [comment]
Hi @mmanoj 

I confirmed the compilation error in my local environment too...
I think using relative include path in Makefile may lead to a missing "libwebsockets.h".
I fixed Makefile, so please check again.

Version of DPDK is 16.04.

**Comment by mmanoj** [comment]
Hi @quiqfield ,

Thank for the quick fix. I will check and confirm.
